/*
  The 10-week intervention program content, extracted from
  Content/Interventions/"Example of 1 10 week program.docx".

  This is an authored CONTENT LIBRARY, not per-student data: eight domains x
  ten weekly sessions, identical for every child. What makes a program
  "tailored" is which domains a student is assigned (from their screening) —
  see lib/programBuilder.ts. Per-student progress will live in the database.

  Bump CONTENT_VERSION whenever a session's wording changes, so programs
  already under way can be pinned to the version they started on.
*/

export const CONTENT_VERSION = 1;

export type Session = {
  /** Week number within this domain's own 10-week progression. */
  week: number;
  title: string;
  youNeed: string;
  whatToDo: string[];
  adultPrompt: string;
  handwritingLink: string;
  observe: string;
};

export type ProgramDomain = {
  id: string;
  /** 1-8, matching the domain numbering in the source document. */
  number: number;
  title: string;
  goal: string;
  sessions: Session[];
};

/** How every session is structured — shown once at the top of a program. */
/*
  The shape of every session, shown once under "Before you start" rather than
  repeated week to week. Each step carries its own timing so a teacher can see
  at a glance that the whole thing fits inside about ten minutes.
*/
export const sessionShape = {
  headline: "Our program will follow this order each week",
  steps: [
    {
      title: "Foundation activity",
      timing: "2\u20135 minutes",
      detail:
        "Prepare the child's foundation skill \u2014 the fundamentals that lie beneath what we see in poor handwriting.",
    },
    {
      title: "Direct handwriting practice",
      timing: "5\u201310 minutes",
      detail:
        "Teach and practise the recommended letters and pre-writing shapes.",
    },
    {
      title: "Check",
      timing: "1\u20132 minutes",
      detail:
        "Identify one current challenge or one strength in the activity.",
    },
  ],
};

/*
  Replaces the old "essential rule". Teachers expect a program to start at A
  and work through the alphabet, so the departure from that is explained up
  front rather than left to be noticed and doubted in week 3.
*/
export const philosophy = {
  title: "Our evidence-based philosophy",
  body: "You'll notice we do not recommend starting with the traditional alphabetic sequence. Our activities recommend letters that are developmentally appropriate for your student \u2014 usually building on vertical and horizontal lines first, before circular and diagonal shapes.",
};

export const howToUse =
  "We recommend you complete one session each week for 10 weeks. Activities can be repeated more than once within the same week. The order we have built is based on your student's areas of challenge identified in the screener, and will provide tailored progressions.";

export const safetyPrinciples = [
  "Use the child\u2019s school-approved letter style and the same short formation language across adults.",
  "Choose an achievable amount. Quality, comfort and successful learning matter more than filling a page.",
  "Change one variable at a time so you can see what helps.",
  "Do not force sensory input, eye closure, movement or hand dominance. Stop any activity that causes pain, distress, dizziness or unsafe movement.",
  "If difficulty is marked, persistent, painful or affecting participation, seek occupational therapy and relevant educational assessment.",
];

/** The three things to watch, from the "Simple progress monitoring" table. */
export const progressMonitoring = [
  {
    record: "Independence",
    examples: "number of adult prompts; ability to set up and begin",
    manageable: "Use the same brief task where possible.",
  },
  {
    record: "Performance",
    examples: "formation, baseline, size, spacing, pressure or copying accuracy",
    manageable: "Choose only one relevant feature each session.",
  },
  {
    record: "Participation",
    examples: "comfort, effort, avoidance, persistence and self-advocacy",
    manageable: "Record what the child says and does\u2014not assumptions.",
  },
];

export const endOfProgramReflection =
  "What has changed in independence, comfort, participation and the selected handwriting feature? Which supports should continue in ordinary classroom writing?";

/** Eight domains, ten sessions each, in the source document's order. */
export const programDomains: ProgramDomain[] = [
  {
    id: "postural-control",
    number: 1,
    title: "Postural Control",
    goal: "Build a steady, comfortable base for controlled hand and finger movements.",
    sessions: [
      {
        week: 1,
        title: "Wall Push and Write",
        youNeed: "A wall, desk, paper and pencil",
        whatToDo: [
          "Complete 10 slow wall pushes with the body straight.",
          "Sit with feet supported, bottom back in the chair and forearms comfortable.",
          "Draw or write for 3-5 minutes. Pause halfway for a body check.",
        ],
        adultPrompt: "“Are your feet supported? Is your body steady? Are your shoulders relaxed?”",
        handwritingLink: "Practise the current pre-writing shape or target letter while maintaining the steady position.",
        observe: "How long can the child remain upright without leaning, wrapping feet around the chair or propping their head?",
      },
      {
        week: 2,
        title: "Chair Push-Up Reset",
        youNeed: "A stable chair, paper and pencil",
        whatToDo: [
          "Place hands beside the hips on the chair seat.",
          "Push down through both hands and gently lift or lighten the bottom for 3 seconds. Repeat 5 times.",
          "Reset the sitting position: feet supported, hips back and paper centred.",
          "Write for 3-5 minutes.",
        ],
        adultPrompt: "“Strong arms, steady body, relaxed writing hand.”",
        handwritingLink: "Form 5 target letters, then use the best one in a short word.",
        observe: "Does the child become steadier after the resistance activity? Stop if there is pain or unsafe movement.",
      },
      {
        week: 3,
        title: "Tall-Kneeling Tracks",
        youNeed: "Low vertical surface or paper secured to a wall",
        whatToDo: [
          "Kneel tall in front of the surface with hips away from the heels.",
          "Draw 5 roads, rainbows or loops without resting on the wall.",
          "Return to the desk and establish the writing position.",
        ],
        adultPrompt: "“Grow tall through your body while your hand does the small work.”",
        handwritingLink: "Write the same line pattern, shape or letter 3-5 times at the desk.",
        observe: "Can the child keep the trunk upright without sitting back or leaning heavily?",
      },
      {
        week: 4,
        title: "Desk Press and Float",
        youNeed: "Desk, chair, paper and pencil",
        whatToDo: [
          "Press both palms firmly into the desk for 5 seconds; repeat 3 times.",
          "Relax the shoulders and pretend the writing hand is light enough to float.",
          "Make one very heavy pencil line, one very light line and one just-right line.",
        ],
        adultPrompt: "“Steady body, soft shoulders, just-right pencil.”",
        handwritingLink: "Practise a target letter using just-right pressure and a stable posture.",
        observe: "Note shoulder elevation, excessive pressure, fatigue or frequent repositioning.",
      },
      {
        week: 5,
        title: "Back-to-Back Body Check",
        youNeed: "Chair, small cushion or rolled towel if needed",
        whatToDo: [
          "Sit with the back gently contacting the chair.",
          "Check five points: feet, knees, hips, back and forearms.",
          "Make a small adjustment to improve comfort and stability.",
          "Complete a short copying task.",
        ],
        adultPrompt: "“Check five, then write.”",
        handwritingLink: "Copy 3 letters or one short word, pausing once to repeat the five-point check.",
        observe: "Which support changes help: footstool, cushion, table height or paper position?",
      },
      {
        week: 6,
        title: "Animal Walk to Table",
        youNeed: "Clear floor space, writing materials",
        whatToDo: [
          "Choose one short animal walk: bear, crab or wheelbarrow with adult support.",
          "Move for 20-30 seconds, rest, then repeat once.",
          "Go directly to the desk and set up a steady writing position.",
        ],
        adultPrompt: "“Big body work first; small pencil work next.”",
        handwritingLink: "Practise the target formation for 3-5 minutes immediately afterwards.",
        observe: "Does brief movement improve readiness, or does it over-excite or fatigue the child?",
      },
      {
        week: 7,
        title: "Vertical Surface Writing",
        youNeed: "Paper or whiteboard fixed at shoulder height",
        whatToDo: [
          "Stand facing the vertical surface with feet hip-width apart.",
          "Draw or write with the elbow slightly away from the body.",
          "Keep the non-writing hand on the surface for support.",
          "Return to seated writing for the final minute.",
        ],
        adultPrompt: "“Feet steady, shoulder strong, fingers moving.”",
        handwritingLink: "Form 5 large target letters vertically, then 3 smaller versions on paper.",
        observe: "Watch for leaning, shoulder fatigue or whole-arm movement when smaller finger movement is needed.",
      },
      {
        week: 8,
        title: "Core-and-Copy Challenge",
        youNeed: "Desk, chair, model card, pencil",
        whatToDo: [
          "Sit away from the chair back for 10 seconds while looking at the model.",
          "Copy one shape or letter.",
          "Rest against the chair, then repeat 4 times.",
          "Use full chair support if the challenge reduces writing quality.",
        ],
        adultPrompt: "“Hold steady, copy carefully, then rest.”",
        handwritingLink: "Copy 4-5 target letters with a brief posture reset between each.",
        observe: "Can the child maintain quality without breath-holding or excessive effort?",
      },
      {
        week: 9,
        title: "Posture Traffic Lights",
        youNeed: "Red, amber and green cards or drawn circles",
        whatToDo: [
          "Show examples: red = unsafe/uncomfortable; amber = becoming tired; green = supported and ready.",
          "The child selects a colour for their current posture.",
          "Make one practical adjustment together.",
          "Recheck after 2 minutes of writing.",
        ],
        adultPrompt: "“What colour is your body? What would help it move toward green?”",
        handwritingLink: "Complete a short word or sentence at the child’s level after the adjustment.",
        observe: "Can the child notice fatigue and request an appropriate support?",
      },
      {
        week: 10,
        title: "Independent Writing Set-Up",
        youNeed: "Child’s usual chair, desk and writing tools",
        whatToDo: [
          "Ask the child to set up without prompts.",
          "Use the sequence: feet, seat, paper, helper hand, pencil.",
          "Give only the least help needed.",
          "Complete a 3-5 minute writing sample and finish with one body check.",
        ],
        adultPrompt: "“Set up five, then begin.”",
        handwritingLink: "Use the regular classroom handwriting target to test transfer.",
        observe: "Record which set-up steps are independent and which still require a visual cue.",
      },
    ],
  },
  {
    id: "bilateral-coordination",
    number: 2,
    title: "Bilateral Coordination",
    goal: "Help the two sides of the body work together, with one hand writing and the other stabilising and positioning the paper.",
    sessions: [
      {
        week: 1,
        title: "Writing Hand and Helper Hand",
        youNeed: "Paper, pencil and two small stickers",
        whatToDo: [
          "Place one sticker where the helper hand should rest and one as a movement target.",
          "Draw horizontal tracks, waves or loops across the page.",
          "Keep the helper hand on the paper while the writing hand moves.",
          "Finish with letters or a short word.",
        ],
        adultPrompt: "“Your writing hand does the work and your helper hand keeps the paper steady.”",
        handwritingLink: "Write 3-5 target letters using the same two-handed position.",
        observe: "Does the helper hand stay active, or does the paper rotate and slide?",
      },
      {
        week: 2,
        title: "Tear, Place and Write",
        youNeed: "Scrap paper, glue, pencil",
        whatToDo: [
          "Hold paper with one hand and tear small pieces with the other.",
          "Swap the stabilising and working roles as needed.",
          "Glue pieces along a left-to-right path.",
          "Trace the path, then write.",
        ],
        adultPrompt: "“One hand holds; one hand works.”",
        handwritingLink: "Write target letters along or beneath the collage path.",
        observe: "Can the child coordinate different roles for each hand?",
      },
      {
        week: 3,
        title: "Pass Across the Body",
        youNeed: "Small beanbag or soft object",
        whatToDo: [
          "Hold the object in the writing hand.",
          "Pass it across the body into the helper hand without swapping at the middle.",
          "Continue in a slow figure-eight pattern for 30 seconds.",
          "Move directly to paper.",
        ],
        adultPrompt: "“Reach across; keep your body facing forward.”",
        handwritingLink: "Draw 5 large horizontal figure eights, then practise the target letter.",
        observe: "Watch for trunk turning, hand switching or avoiding the midline.",
      },
      {
        week: 4,
        title: "Paper Turn Partner",
        youNeed: "Paper with four large shapes, crayons",
        whatToDo: [
          "The helper hand turns the paper while the writing hand colours each shape.",
          "Pause before each turn and name each hand’s job.",
          "Keep the crayon in the writing hand.",
          "Return the page to the usual writing angle.",
        ],
        adultPrompt: "“Writing hand colours; helper hand turns.”",
        handwritingLink: "Practise a curved letter such as c, o, a or d after the rotation task.",
        observe: "Can the child rotate the paper smoothly without transferring the tool?",
      },
      {
        week: 5,
        title: "Lacing then Letter Lines",
        youNeed: "Lacing card or card with punched holes, lace, pencil",
        whatToDo: [
          "Hold the card with the helper hand.",
          "Thread in and out with the working hand for 2 minutes.",
          "Keep the card near the midline.",
          "Move to a left-to-right pencil task.",
        ],
        adultPrompt: "“Helper hand holds steady while the other hand moves.”",
        handwritingLink: "Write a row of the target letter, moving across the line without changing hands.",
        observe: "Observe hand dominance, stabilisation and smooth movement across the page.",
      },
      {
        week: 6,
        title: "Two-Hand Rhythm",
        youNeed: "Desk and writing materials",
        whatToDo: [
          "Tap both hands together, then alternate right-left for 20 seconds.",
          "Tap the helper hand steadily while the writing hand traces a large pattern in the air.",
          "Stop the tapping and place both hands in their writing jobs.",
        ],
        adultPrompt: "“Together, alternate, then writing jobs.”",
        handwritingLink: "Write the target formation 5 times with the helper hand anchored.",
        observe: "Does rhythm help organisation, or is it too demanding? Simplify if needed.",
      },
      {
        week: 7,
        title: "Ruler Roads",
        youNeed: "Ruler, paper and pencil",
        whatToDo: [
          "Use the helper hand to press a ruler firmly in place.",
          "Use the writing hand to draw 4 horizontal roads.",
          "Move the ruler down the page without swapping hand roles.",
          "Add letters on each road.",
        ],
        adultPrompt: "“Hold it still; draw across.”",
        handwritingLink: "Place 3-5 target letters on each road, attending to baseline placement.",
        observe: "Can the child grade stabilising force without the ruler slipping?",
      },
      {
        week: 8,
        title: "Sticker Trail Across Midline",
        youNeed: "Small stickers, paper, pencil",
        whatToDo: [
          "Place stickers from the child’s helper-hand side across to the writing-hand side.",
          "Keep the paper centred and peel/place with the writing hand.",
          "Connect the stickers from left to right with one continuous line.",
          "Add a writing task below.",
        ],
        adultPrompt: "“Keep your body facing forward while your hand travels across.”",
        handwritingLink: "Copy a short letter sequence or word from left to right.",
        observe: "Note midline avoidance, body rotation or loss of helper-hand support.",
      },
      {
        week: 9,
        title: "Fold, Press and Label",
        youNeed: "Paper, pencil",
        whatToDo: [
          "Hold the paper with both hands and fold it in half.",
          "Use both hands to press the crease from the centre outward.",
          "Open it and stabilise with the helper hand.",
          "Write or draw on each side.",
        ],
        adultPrompt: "“Both hands prepare; then each hand has its job.”",
        handwritingLink: "Write target letters on the left and right halves without switching hands.",
        observe: "Can the child maintain a chosen writing hand across both sides of space?",
      },
      {
        week: 10,
        title: "Independent Two-Hand Check",
        youNeed: "Usual classroom writing task",
        whatToDo: [
          "Before writing, ask the child to show each hand’s job.",
          "Position and angle the paper independently.",
          "Write for 3-5 minutes.",
          "Pause once to check whether the helper hand is still assisting.",
        ],
        adultPrompt: "“Show me your writing hand and your helper hand.”",
        handwritingLink: "Complete the usual handwriting target or one short classroom sentence.",
        observe: "Record independence, paper stability and movement across the full line.",
      },
    ],
  },
  {
    id: "fine-motor-control",
    number: 3,
    title: "Fine Motor Control",
    goal: "Develop precise, efficient finger movements and pencil control while avoiding unnecessary fatigue.",
    sessions: [
      {
        week: 1,
        title: "Pinch, Roll and Write",
        youNeed: "Playdough, pencil and paper",
        whatToDo: [
          "Pinch playdough 10 times with thumb and index finger.",
          "Roll small balls with the fingertips.",
          "Make a thin snake and shape the target letter.",
          "Trace it while saying the formation cue.",
        ],
        adultPrompt: "“Small finger movements first, then use those fingers to control your pencil.”",
        handwritingLink: "Write the same letter 3-5 times with a pencil.",
        observe: "Look for isolated fingertip movement rather than movement from the whole arm.",
      },
      {
        week: 2,
        title: "Peg Pick-Up Patterns",
        youNeed: "Small pegs or clips, card, pencil",
        whatToDo: [
          "Pick up 8 pegs using thumb and index finger.",
          "Place them around card in a simple colour pattern.",
          "Remove them with the same fingers.",
          "Shake hands gently and write.",
        ],
        adultPrompt: "“Pinch, place, release.”",
        handwritingLink: "Practise 5 target letters with slow, controlled starts and stops.",
        observe: "Does the child use a neat fingertip pinch or press objects into the palm?",
      },
      {
        week: 3,
        title: "Coin Posting and In-Hand Shift",
        youNeed: "Large coins/counters, container with slot",
        whatToDo: [
          "Pick up one counter at a time with fingertips.",
          "For a challenge, hold two in the palm and move one to the fingertips.",
          "Post 8-10 counters.",
          "Move to the pencil without a long delay.",
        ],
        adultPrompt: "“Move it from your palm to your fingertips.”",
        handwritingLink: "Write a short row of the target letter, keeping movements small.",
        observe: "Watch for dropping, using the other hand to reposition or excessive tension.",
      },
      {
        week: 4,
        title: "Tiny Tongs to Pencil",
        youNeed: "Child-safe tongs, pom-poms, two bowls",
        whatToDo: [
          "Move 10 pom-poms between bowls using tongs.",
          "Keep the wrist neutral and elbow near the body.",
          "Use slower movements for the final three.",
          "Take up the pencil with a comfortable grip.",
        ],
        adultPrompt: "“Squeeze gently and move carefully.”",
        handwritingLink: "Trace then independently write the target formation.",
        observe: "Can the child grade force and release accurately?",
      },
      {
        week: 5,
        title: "Finger Walk Maze",
        youNeed: "Simple printed or hand-drawn maze",
        whatToDo: [
          "Walk index and middle fingers through a large maze.",
          "Repeat through a smaller maze.",
          "Trace the route with pencil without touching the edges.",
          "Finish with a formation task.",
        ],
        adultPrompt: "“Slow fingers stay on the path.”",
        handwritingLink: "Write 3-5 letters requiring similar directional control.",
        observe: "Compare fingertip control with pencil control; note speed-accuracy trade-offs.",
      },
      {
        week: 6,
        title: "Dot-to-Dot Control",
        youNeed: "Paper with 6-10 dots, pencil",
        whatToDo: [
          "Touch each dot with the pencil without drawing.",
          "Connect dots slowly using straight or curved lines.",
          "Pause at each dot instead of overshooting.",
          "Use the pattern as a warm-up for letters.",
        ],
        adultPrompt: "“Travel, stop, then change direction.”",
        handwritingLink: "Practise a target letter with clear stopping or turning points.",
        observe: "Does the child overshoot, press too hard or rush transitions?",
      },
      {
        week: 7,
        title: "Pencil Twirl and Set",
        youNeed: "Short pencil or crayon",
        whatToDo: [
          "Pick up the pencil from the desk with one hand.",
          "Use the fingers to turn it so the tip faces the paper.",
          "Practise moving fingers slightly up and down the shaft.",
          "Settle into a comfortable functional grip.",
        ],
        adultPrompt: "“Let your fingers organise the pencil.”",
        handwritingLink: "Write 5 target letters without repeatedly readjusting the grip.",
        observe: "Can the child position the tool efficiently using one hand?",
      },
      {
        week: 8,
        title: "Mini Pattern Boxes",
        youNeed: "Paper divided into small boxes, fine marker or pencil",
        whatToDo: [
          "Demonstrate one small pattern: lines, bumps, waves or loops.",
          "Copy the pattern in 4 boxes, staying within boundaries.",
          "Slow down for accuracy rather than filling every space.",
          "Choose the closest matching letter family.",
        ],
        adultPrompt: "“Small box, small controlled movement.”",
        handwritingLink: "Write one target letter in each of 4-6 boxes.",
        observe: "Observe size control, boundary awareness and finger versus wrist movement.",
      },
      {
        week: 9,
        title: "Paper Clip Chain and Write",
        youNeed: "Large paper clips, pencil and paper",
        whatToDo: [
          "Link 6-8 paper clips using both hands.",
          "Unlink them using thumb-index control.",
          "Rest and stretch fingers briefly.",
          "Begin the writing task with relaxed pressure.",
        ],
        adultPrompt: "“Strong enough to connect; gentle enough to write.”",
        handwritingLink: "Practise the target letter, then write one short word.",
        observe: "Check for fatigue, joint locking or an overly tight pencil grasp.",
      },
      {
        week: 10,
        title: "Precision Transfer Challenge",
        youNeed: "Choice of small classroom objects, cup, pencil",
        whatToDo: [
          "The child chooses an appropriate fingertip tool: fingers, pegs or tongs.",
          "Transfer 10 objects accurately.",
          "Explain which movement helped most.",
          "Complete a timed-but-unhurried writing sample.",
        ],
        adultPrompt: "“Choose, control, then write.”",
        handwritingLink: "Complete the regular letter or word target for 3-5 minutes.",
        observe: "Compare control, comfort and legibility with Week 1; speed is secondary.",
      },
    ],
  },
  {
    id: "sensory-regulation",
    number: 4,
    title: "Sensory Regulation and Body Awareness",
    goal: "Help the child notice body state, pencil pressure and sensory needs, then choose a safe strategy that supports writing.",
    sessions: [
      {
        week: 1,
        title: "Push, Breathe, Check and Write",
        youNeed: "Desk, chair, paper and pencil",
        whatToDo: [
          "Push hands firmly into the chair or desk for 5 seconds; repeat 3 times.",
          "Take 3 slow breaths.",
          "Check readiness, hand comfort and pencil pressure.",
          "Make faint, dark and just-right lines.",
        ],
        adultPrompt: "“Is your body ready? Is your hand comfortable? Is your pressure just right?”",
        handwritingLink: "Write for 3-5 minutes and check pressure halfway through.",
        observe: "Which input helps this individual child? Never assume one sensory strategy suits everyone.",
      },
      {
        week: 2,
        title: "Heavy-Light-Just Right",
        youNeed: "Pencil and paper",
        whatToDo: [
          "Draw three roads: too light, too heavy and just right.",
          "Compare which is easiest to see and does not mark through the page.",
          "Circle the just-right example.",
          "Use that pressure for writing.",
        ],
        adultPrompt: "“Can your pencil leave a clear mark without digging into the paper?”",
        handwritingLink: "Write 5 target letters and check the back of the page.",
        observe: "Note pressure consistency, broken pencil tips, hand pain or faint marks.",
      },
      {
        week: 3,
        title: "Body Engine Check",
        youNeed: "Three simple cards: slow, just right, fast",
        whatToDo: [
          "The child identifies whether their body feels slow, just right or fast.",
          "Choose one short strategy: 10 pushes for slow/fast, or 3 breaths for fast.",
          "Recheck the body engine.",
          "Begin a small writing task.",
        ],
        adultPrompt: "“What speed is your body? What could help?”",
        handwritingLink: "Practise the current shape or letter for 3 minutes.",
        observe: "Can the child identify state and whether the chosen strategy changed it?",
      },
      {
        week: 4,
        title: "Texture Choice then Pencil",
        youNeed: "Two acceptable tactile materials, writing tools",
        whatToDo: [
          "Offer a choice of brief tactile input, such as playdough or a textured strip.",
          "Explore for 60 seconds without forcing contact.",
          "Wipe hands if preferred.",
          "Transition immediately to paper.",
        ],
        adultPrompt: "“Choose what helps your hands feel ready.”",
        handwritingLink: "Trace a formation once with the finger, then write it 3-5 times.",
        observe: "Record preferences and signs of distress; sensory input must be optional.",
      },
      {
        week: 5,
        title: "Joint Position Copy",
        youNeed: "No equipment, then paper and pencil",
        whatToDo: [
          "Adult makes 3 simple arm/hand positions for the child to copy.",
          "Child closes eyes briefly and tries one familiar position if comfortable.",
          "Open eyes and compare.",
          "Move to pencil grip and hand-position awareness.",
        ],
        adultPrompt: "“Where are your fingers, wrist and elbow?”",
        handwritingLink: "Write the target letter while noticing a relaxed wrist and supported forearm.",
        observe: "Can the child sense and adjust body position without excessive visual checking?",
      },
      {
        week: 6,
        title: "Breathing Line",
        youNeed: "Paper and pencil",
        whatToDo: [
          "Breathe in while moving the pencil up a long line.",
          "Breathe out while moving down or around a curve.",
          "Repeat slowly 4 times.",
          "Reduce the movement to letter size.",
        ],
        adultPrompt: "“Slow breath, slow line.”",
        handwritingLink: "Practise a letter with a similar stroke pattern, without making breathing a rigid rule.",
        observe: "Does paced breathing reduce rushing or increase frustration? Adapt accordingly.",
      },
      {
        week: 7,
        title: "Pressure Sandwich",
        youNeed: "Two sheets of paper, pencil, firm writing board",
        whatToDo: [
          "Write once on a soft stack and once on a firm surface.",
          "Compare how each feels and looks.",
          "Choose the surface that supports control.",
          "Set up the chosen surface for writing.",
        ],
        adultPrompt: "“Which surface helps your pencil feel just right?”",
        handwritingLink: "Write the target formation 5 times on the preferred surface.",
        observe: "Note whether surface firmness changes force, comfort or legibility.",
      },
      {
        week: 8,
        title: "Movement Menu",
        youNeed: "Visual menu with 3 safe options",
        whatToDo: [
          "Offer three 30-second choices: wall pushes, marching or hand presses.",
          "Child selects one and completes it.",
          "Rate readiness before and after using thumbs down/side/up.",
          "Begin writing.",
        ],
        adultPrompt: "“Choose one way to get ready, then check if it helped.”",
        handwritingLink: "Complete 3-5 minutes of direct handwriting practice.",
        observe: "Build self-knowledge: the goal is not compliance with a prescribed movement.",
      },
      {
        week: 9,
        title: "Hand Comfort Detective",
        youNeed: "Pencil choices, optional grip, paper",
        whatToDo: [
          "Check for pain, tiredness, sweat, tight grip or finger pressure.",
          "Try one change only: tool thickness, grip, paper angle or brief rest.",
          "Compare comfort after one minute.",
          "Keep the helpful change.",
        ],
        adultPrompt: "“What is your hand telling you?”",
        handwritingLink: "Write one short word or letter row before and after the change.",
        observe: "Document pain or persistent fatigue and refer for assessment when indicated.",
      },
      {
        week: 10,
        title: "My Ready-to-Write Plan",
        youNeed: "Small visual plan card",
        whatToDo: [
          "The child chooses a personal 3-step plan: body check, one strategy, pencil-pressure check.",
          "Follow the plan with minimal adult prompting.",
          "Write for 3-5 minutes.",
          "Reflect on what helped.",
        ],
        adultPrompt: "“Use your plan: check, choose, write.”",
        handwritingLink: "Use the regular classroom handwriting target to practise independent regulation.",
        observe: "Can the child select and use a helpful strategy without over-relying on adult direction?",
      },
    ],
  },
  {
    id: "visual-perception",
    number: 5,
    title: "Visual Perception",
    goal: "Strengthen recognition of letter features, direction, position and visual patterns so the child can discriminate forms accurately.",
    sessions: [
      {
        week: 1,
        title: "Letter Detective",
        youNeed: "Page with target letter mixed among similar letters",
        whatToDo: [
          "Show the target and name its distinguishing features.",
          "Find and circle every correct example.",
          "Identify letters facing the wrong way or with a changed feature.",
          "Explain how each match was found.",
        ],
        adultPrompt: "“Which way does it face, and where is the tall part?”",
        handwritingLink: "Write the target letter correctly 3-5 times.",
        observe: "Can the child describe visual features rather than guess from context?",
      },
      {
        week: 2,
        title: "Same or Different?",
        youNeed: "Pairs of shapes or letters",
        whatToDo: [
          "Show 6 pairs one at a time.",
          "Child says same or different and points to the changed feature.",
          "Include changes in size, direction, closure or line length.",
          "Finish with the target form.",
        ],
        adultPrompt: "“Look from top to bottom. What changed?”",
        handwritingLink: "Copy the correct target beside each matching pair.",
        observe: "Which differences are missed consistently?",
      },
      {
        week: 3,
        title: "Find the Letter in Print",
        youNeed: "Book, worksheet or classroom text, highlighter",
        whatToDo: [
          "Choose one target letter.",
          "Scan one short line left to right.",
          "Highlight 5 examples.",
          "Compare fonts while identifying the essential features.",
        ],
        adultPrompt: "“The font may change, but what stays the same?”",
        handwritingLink: "Write the target letter in the child’s taught school style.",
        observe: "Can the child recognise the letter across common fonts without copying unsuitable forms?",
      },
      {
        week: 4,
        title: "Complete the Missing Part",
        youNeed: "Partially drawn shapes or letters",
        whatToDo: [
          "Show a familiar form with one stroke missing.",
          "Child identifies and adds the missing part.",
          "Compare with a complete model.",
          "Repeat with 4-5 examples.",
        ],
        adultPrompt: "“What part does this letter need?”",
        handwritingLink: "Write the complete target independently 3 times.",
        observe: "Observe whether the child notices missing closures, stems or crosses.",
      },
      {
        week: 5,
        title: "Direction Sort",
        youNeed: "Cards showing letters/shapes in correct and reversed orientations",
        whatToDo: [
          "Place a correct model at the top.",
          "Sort cards into matches and not-yet matches.",
          "Rotate cards physically to test whether orientation matters.",
          "State the direction cue.",
        ],
        adultPrompt: "“Match the direction, not just the pieces.”",
        handwritingLink: "Write the correctly oriented target 5 times using a formation cue.",
        observe: "Avoid shaming reversals; note whether explicit directional language helps.",
      },
      {
        week: 6,
        title: "Visual Memory Flash",
        youNeed: "Letter or short pattern card, blank paper",
        whatToDo: [
          "Show the card for 3 seconds.",
          "Hide it and ask the child to describe it.",
          "Draw or select the remembered form.",
          "Reveal, compare and correct.",
        ],
        adultPrompt: "“Look, picture it in your mind, then show me.”",
        handwritingLink: "Write the target from memory, then check against the model.",
        observe: "How much visual information can the child retain accurately?",
      },
      {
        week: 7,
        title: "Letter Feature Sort",
        youNeed: "Mixed letter cards",
        whatToDo: [
          "Choose one feature: tall, tail, curve, straight line or closed shape.",
          "Sort 8-10 letters by that feature.",
          "Explain any letters that fit more than one group.",
          "Select one target to write.",
        ],
        adultPrompt: "“What visual feature helped you sort it?”",
        handwritingLink: "Write 3 letters from the chosen group and name their shared feature.",
        observe: "Can the child attend to component features and categories?",
      },
      {
        week: 8,
        title: "Busy Page Search",
        youNeed: "Simple visual search page",
        whatToDo: [
          "Agree on one target before starting.",
          "Use a finger or card to track each row.",
          "Mark targets systematically.",
          "Stop after 2 minutes and check misses together.",
        ],
        adultPrompt: "“Scan in order so your eyes know where to go next.”",
        handwritingLink: "Copy a short sequence of the located target letters.",
        observe: "Note scanning pattern, skipped areas and distractibility.",
      },
      {
        week: 9,
        title: "Model Match and Check",
        youNeed: "Three letter models: one correct, two subtly altered",
        whatToDo: [
          "Compare starting point, stroke direction, closure and proportion.",
          "Choose the model that matches the taught formation.",
          "Explain why.",
          "Correct one altered model.",
        ],
        adultPrompt: "“Which model follows our letter rule?”",
        handwritingLink: "Write the chosen letter 3-5 times from the correct model.",
        observe: "Can the child use a consistent checking routine?",
      },
      {
        week: 10,
        title: "Independent Letter Detective",
        youNeed: "Short authentic writing sample and model alphabet",
        whatToDo: [
          "Child selects one letter to inspect in their own writing.",
          "Find all examples of that letter.",
          "Compare them with the taught model.",
          "Choose one achievable visual feature to improve.",
        ],
        adultPrompt: "“Find it, compare it, improve one thing.”",
        handwritingLink: "Rewrite 3 examples or one short word containing the target.",
        observe: "Can the child apply visual discrimination to their own work without global criticism?",
      },
    ],
  },
  {
    id: "visual-motor-integration",
    number: 6,
    title: "Visual-Motor Integration",
    goal: "Coordinate what the eyes see with controlled hand movements for copying shapes, letters and words.",
    sessions: [
      {
        week: 1,
        title: "Look, Copy, Check",
        youNeed: "Model of a shape, pattern or letter; paper and pencil",
        whatToDo: [
          "Look carefully at a model the child can almost copy.",
          "Copy it beside or underneath.",
          "Compare starting point, direction, size and position.",
          "Repeat 3-5 times with support as needed.",
        ],
        adultPrompt: "“Look at the model, copy it, then check what is the same or different.”",
        handwritingLink: "Progress from pre-writing shape to pattern, letter or short word.",
        observe: "Identify whether errors arise during looking, planning, movement or checking.",
      },
      {
        week: 2,
        title: "Near-Point Shape Copy",
        youNeed: "Card with 4 shapes placed beside paper",
        whatToDo: [
          "Point to the first shape and trace it in the air.",
          "Copy it directly beside the model.",
          "Check one feature only.",
          "Repeat through the short sequence.",
        ],
        adultPrompt: "“Eyes to model, eyes to paper, then check.”",
        handwritingLink: "Replace the final shape with the current target letter.",
        observe: "Watch for losing place, rotation, size changes or added/omitted strokes.",
      },
      {
        week: 3,
        title: "Path to Letter",
        youNeed: "Simple paths that resemble letter strokes",
        whatToDo: [
          "Trace a wide path with the finger.",
          "Draw through it with pencil, staying between edges.",
          "Narrow the path for the next attempt.",
          "Remove the path and form the related letter.",
        ],
        adultPrompt: "“Follow the path, then make the movement yourself.”",
        handwritingLink: "Practise a letter sharing the same straight, curve or diagonal movement.",
        observe: "Does performance change when visual boundaries are removed?",
      },
      {
        week: 4,
        title: "Block Pattern Copy",
        youNeed: "4-6 coloured blocks or squares, crayons",
        whatToDo: [
          "Build or show a simple 2D pattern.",
          "Child copies the arrangement.",
          "Draw the pattern on grid paper.",
          "Compare position and sequence.",
        ],
        adultPrompt: "“Look where each piece goes, then copy it on paper.”",
        handwritingLink: "Copy a 2-3 letter sequence beneath the pattern.",
        observe: "Note spatial position, sequencing and eye-to-hand shifts.",
      },
      {
        week: 5,
        title: "Finish the Pattern",
        youNeed: "Paper with repeated lines, curves or shapes",
        whatToDo: [
          "Name the repeating unit.",
          "Trace one example.",
          "Continue the pattern across a short row.",
          "Keep size and spacing as even as possible.",
        ],
        adultPrompt: "“See the pattern, keep it going.”",
        handwritingLink: "Continue a repeated target letter across a ruled line.",
        observe: "Observe rhythm, spacing, size and drift from the baseline.",
      },
      {
        week: 6,
        title: "Copy from the Board - One Step",
        youNeed: "Large model displayed 1-2 metres away",
        whatToDo: [
          "Show one shape or letter only.",
          "Child looks, says the movement cue, then looks down to copy.",
          "Check immediately against the model.",
          "Repeat 4 times.",
        ],
        adultPrompt: "“Look, say it, write it, check it.”",
        handwritingLink: "Copy the current target letter from a distant model.",
        observe: "How many gaze shifts are needed, and does the child retain the form?",
      },
      {
        week: 7,
        title: "Mirror My Movement",
        youNeed: "Whiteboard or paper for adult and child",
        whatToDo: [
          "Adult draws one slow stroke.",
          "Child copies it at the same time, then independently.",
          "Combine two strokes into a shape or letter.",
          "Reduce adult movement support.",
        ],
        adultPrompt: "“Watch my movement, then make yours.”",
        handwritingLink: "Form the target letter once together and 3 times independently.",
        observe: "Can the child translate a demonstrated movement into their own motor action?",
      },
      {
        week: 8,
        title: "Grid Copy",
        youNeed: "Simple grid with a shape or letter, blank matching grid",
        whatToDo: [
          "Find the starting square.",
          "Copy one segment at a time into the matching square.",
          "Check overall size and position.",
          "Repeat with a simpler or harder grid as appropriate.",
        ],
        adultPrompt: "“Same square, same movement.”",
        handwritingLink: "Copy one large target letter on grid, then write it without the grid.",
        observe: "Note spatial mapping and whether the grid supports or overloads the child.",
      },
      {
        week: 9,
        title: "Word Copy in Chunks",
        youNeed: "Near-point model of a familiar 3-5 letter word",
        whatToDo: [
          "Read and point to the word.",
          "Copy one or two letters at a time rather than repeatedly looking after every stroke.",
          "Check sequence and spacing.",
          "Correct only one selected feature.",
        ],
        adultPrompt: "“Look at a small chunk, copy it, then check.”",
        handwritingLink: "Copy the familiar word once or twice using taught formations.",
        observe: "Observe place-keeping, omissions, repeated letters and copying efficiency.",
      },
      {
        week: 10,
        title: "Independent Copy Strategy",
        youNeed: "Short model matched to the child’s level",
        whatToDo: [
          "Child chooses the best strategy: model beside paper, finger tracker, verbal cue or chunking.",
          "Copy for 3 minutes.",
          "Compare model and copy using a simple checklist.",
          "Name one successful strategy.",
        ],
        adultPrompt: "“Choose how you will look, copy and check.”",
        handwritingLink: "Copy a short word or sentence appropriate to the child’s current level.",
        observe: "Can the child choose and apply a support that improves accuracy?",
      },
    ],
  },
  {
    id: "attention-executive-function",
    number: 7,
    title: "Attention and Executive Function",
    goal: "Support starting, sustaining, sequencing and checking during brief, achievable handwriting tasks.",
    sessions: [
      {
        week: 1,
        title: "Three-Step Writing Mission",
        youNeed: "Three-box checklist, pencil and paper",
        whatToDo: [
          "Get ready: pencil, paper and sitting position.",
          "Write one small, clearly defined amount.",
          "Check one feature only.",
          "Tick or cover each step.",
        ],
        adultPrompt: "“First get ready, then write, then check.”",
        handwritingLink: "Use one target such as formation, spacing or placement.",
        observe: "Can the child begin and complete the sequence with reduced prompting?",
      },
      {
        week: 2,
        title: "First-Then Writing",
        youNeed: "First-then card and writing materials",
        whatToDo: [
          "Show: First 3 letters; then a brief preferred classroom choice.",
          "State the finish point clearly.",
          "Complete the writing with one reminder at most.",
          "Acknowledge completion and move to then.",
        ],
        adultPrompt: "“First three careful letters, then your choice.”",
        handwritingLink: "Practise 3-5 target formations, prioritising quality over quantity.",
        observe: "Does a visible endpoint reduce avoidance and negotiation?",
      },
      {
        week: 3,
        title: "Beat Your Start Time",
        youNeed: "Visual timer, materials ready",
        whatToDo: [
          "Set a realistic goal to begin within 30 seconds.",
          "Start timer after the instruction.",
          "Child follows a two-step setup cue.",
          "Celebrate beginning, not speed of writing.",
        ],
        adultPrompt: "“Ready, set up, begin.”",
        handwritingLink: "Complete a 2-3 minute target practice after starting.",
        observe: "Record latency to begin without turning it into pressure or competition.",
      },
      {
        week: 4,
        title: "One Goal Spotlight",
        youNeed: "Small goal card",
        whatToDo: [
          "Choose one observable goal: start at top, sit on line or leave a finger space.",
          "Place the card beside the paper.",
          "Write for 3 minutes.",
          "Highlight one example that met the goal.",
        ],
        adultPrompt: "“Today our spotlight is only on ____.”",
        handwritingLink: "Use the current letter, word or sentence target.",
        observe: "Can the child maintain one goal without being overloaded by multiple corrections?",
      },
      {
        week: 5,
        title: "Stop-Plan-Do-Check",
        youNeed: "Four-icon strip",
        whatToDo: [
          "Stop and listen to the short task.",
          "Plan what is needed and how much to complete.",
          "Do the task.",
          "Check the one agreed feature.",
        ],
        adultPrompt: "“Stop, plan, do, check.”",
        handwritingLink: "Write one small unit such as 5 letters or one sentence.",
        observe: "Which stage needs adult cueing: listening, planning, doing or checking?",
      },
      {
        week: 6,
        title: "Writing Sprint and Reset",
        youNeed: "Timer",
        whatToDo: [
          "Agree on 60-90 seconds of careful writing.",
          "Write until the timer finishes.",
          "Take a 20-second posture/hand reset.",
          "Repeat once.",
        ],
        adultPrompt: "“Careful writing until the bell, then reset.”",
        handwritingLink: "Practise the same formation in two short bursts.",
        observe: "Does chunking improve persistence and quality compared with one longer demand?",
      },
      {
        week: 7,
        title: "Find Your Place",
        youNeed: "Model text, tracking card or ruler",
        whatToDo: [
          "Use the card under the line being copied.",
          "Point to the next letter or word before looking down.",
          "Copy a small chunk.",
          "Move the tracker and repeat.",
        ],
        adultPrompt: "“Point, remember a chunk, write, find your place.”",
        handwritingLink: "Copy one familiar word or a very short sentence.",
        observe: "Note loss of place, omissions and whether the tracker helps.",
      },
      {
        week: 8,
        title: "Error Detective - One Check",
        youNeed: "Writing sample and coloured pencil",
        whatToDo: [
          "Tell the child exactly what to search for.",
          "Scan the sample left to right.",
          "Circle one success and correct one error.",
          "Stop checking when the chosen feature is complete.",
        ],
        adultPrompt: "“Detect only ____. Ignore everything else today.”",
        handwritingLink: "Check formation, spacing, baseline or size—not all at once.",
        observe: "Can the child inhibit unrelated corrections and complete a focused review?",
      },
      {
        week: 9,
        title: "Choice Within Structure",
        youNeed: "Two equivalent writing options",
        whatToDo: [
          "Offer two choices that meet the same goal: pencil colour, word choice or order.",
          "Child chooses quickly.",
          "Follow the familiar get ready-write-check sequence.",
          "Reflect on whether the choice helped starting.",
        ],
        adultPrompt: "“You choose A or B; both practise the same skill.”",
        handwritingLink: "Complete the target practice using the chosen option.",
        observe: "Does bounded choice improve engagement without distracting from the goal?",
      },
      {
        week: 10,
        title: "Independent Writing Mission",
        youNeed: "Laminated three- or four-step visual",
        whatToDo: [
          "Adult gives the goal and endpoint once.",
          "Child organises tools and follows the visual.",
          "Complete 3-5 minutes of writing.",
          "Self-check one feature and report one success.",
        ],
        adultPrompt: "“Use your mission card and tell me when you have checked.”",
        handwritingLink: "Use the usual classroom handwriting task.",
        observe: "Record number of prompts, time on task and independent self-checking compared with Week 1.",
      },
    ],
  },
  {
    id: "language-letter-knowledge",
    number: 8,
    title: "Language and Letter Knowledge",
    goal: "Connect the letter’s name, sound, visual identity and consistent movement language to support learning and recall.",
    sessions: [
      {
        week: 1,
        title: "Say It, Hear It, Form It",
        youNeed: "Letter card, pencil and paper",
        whatToDo: [
          "Show and name the target letter.",
          "Say its most common sound and a familiar example word.",
          "Give a short consistent formation cue.",
          "Trace or form while saying the cue, then write independently.",
        ],
        adultPrompt: "“Say it, hear it, form it.”",
        handwritingLink: "Write the target several times and use it in a word when appropriate.",
        observe: "Can the child link name, sound, appearance and motor sequence?",
      },
      {
        week: 2,
        title: "Formation Story",
        youNeed: "Target letter card",
        whatToDo: [
          "Create one brief movement story based on the school’s formation language.",
          "Adult demonstrates while saying it.",
          "Child repeats the cue while air-writing.",
          "Move to paper and gradually shorten the cue.",
        ],
        adultPrompt: "“Tell your hand the letter story.”",
        handwritingLink: "Write 3-5 target letters using the same cue.",
        observe: "Does verbal mediation support recall, or is a shorter cue needed?",
      },
      {
        week: 3,
        title: "Sound Hunt and Write",
        youNeed: "Classroom objects or picture cards",
        whatToDo: [
          "Say the target sound.",
          "Find 3 objects/pictures beginning with that sound.",
          "Name the initial sound clearly.",
          "Return to the letter card and formation cue.",
        ],
        adultPrompt: "“Hear the sound, find the word, write the letter.”",
        handwritingLink: "Write the target initial beside or under each picture.",
        observe: "Can the child isolate the sound and retrieve the matching grapheme?",
      },
      {
        week: 4,
        title: "Letter Name or Sound?",
        youNeed: "Letter cards",
        whatToDo: [
          "Show 5 familiar cards.",
          "Adult asks specifically for the name or sound.",
          "Child answers, then sorts cards by a selected feature.",
          "Choose one card for formation practice.",
        ],
        adultPrompt: "“Listen: am I asking for its name or its sound?”",
        handwritingLink: "Write the chosen target 3 times and say both name and sound once.",
        observe: "Note confusion between letter labels and phonemes.",
      },
      {
        week: 5,
        title: "Explain the Movement",
        youNeed: "Letter model and paper",
        whatToDo: [
          "Adult deliberately forms the letter correctly.",
          "Child explains the starting point and movement in their own words.",
          "Agree on a concise accurate cue.",
          "Child teaches the adult, then writes.",
        ],
        adultPrompt: "“Be the teacher: where do I start and where do I go?”",
        handwritingLink: "Write 3-5 examples while softly repeating the agreed cue.",
        observe: "Can the child sequence and express the motor plan?",
      },
      {
        week: 6,
        title: "Build a Word Family",
        youNeed: "Target rime or simple word cards",
        whatToDo: [
          "Choose a familiar pattern appropriate to literacy level.",
          "Change the initial letter to create 2-4 words.",
          "Read each word aloud.",
          "Attend to the target letter’s formation within the word.",
        ],
        adultPrompt: "“Change one sound, keep the pattern.”",
        handwritingLink: "Write 2-4 short words with careful target-letter formation.",
        observe: "Keep literacy demand within the child’s skill so handwriting remains the main goal.",
      },
      {
        week: 7,
        title: "Uppercase-Lowercase Partners",
        youNeed: "Mixed uppercase and lowercase cards",
        whatToDo: [
          "Match 5 uppercase letters with their lowercase partners.",
          "Name each pair and discuss whether they look similar or different.",
          "Select one pair.",
          "Demonstrate distinct formation cues.",
        ],
        adultPrompt: "“Same letter name, two forms.”",
        handwritingLink: "Write the uppercase once and lowercase 3 times, using correct cues.",
        observe: "Can the child retrieve both forms without blending their motor patterns?",
      },
      {
        week: 8,
        title: "Listen and Select",
        youNeed: "Three letter cards including target",
        whatToDo: [
          "Adult says a letter name, sound or formation cue.",
          "Child selects the matching card.",
          "Explain which clue helped.",
          "Increase similarity only when successful.",
        ],
        adultPrompt: "“Listen for the clue, then choose.”",
        handwritingLink: "Write the selected target from memory and check the card.",
        observe: "Which verbal cue most reliably triggers correct recall?",
      },
      {
        week: 9,
        title: "Letter in a Meaningful Word",
        youNeed: "Child’s name or high-interest familiar words",
        whatToDo: [
          "Choose a meaningful word containing the target.",
          "Say, segment or locate the target within it.",
          "Highlight the target in the model.",
          "Practise the letter, then the whole word.",
        ],
        adultPrompt: "“Find our letter inside a word that matters to you.”",
        handwritingLink: "Write the target 3 times, then write the meaningful word once.",
        observe: "Does meaningful context improve recall without increasing spelling load?",
      },
      {
        week: 10,
        title: "Teach-Back Letter Expert",
        youNeed: "Known target cards and blank paper",
        whatToDo: [
          "Child chooses one letter learned during the program.",
          "Teach its name, sound, visual features and formation cue to an adult or peer.",
          "Demonstrate it once.",
          "Write it in a word and self-check.",
        ],
        adultPrompt: "“You are the letter expert—teach all four parts.”",
        handwritingLink: "Produce the letter independently and use it in an achievable word.",
        observe: "Can the child retrieve and integrate letter knowledge without the original prompts?",
      },
    ],
  },
];

export const programDomainById: Record<string, ProgramDomain> =
  Object.fromEntries(programDomains.map((d) => [d.id, d]));
